package dlsim.DLSim;
/* Generated by Together */

public class Signal {
    boolean b;

    public Signal (boolean value)
	{
        this.b=value;
    }
    public boolean getValue()
    {
        return b;
	}
    public boolean equals(Signal a)
    {
        return a.getValue()==b;
    }
}
