package dlsim.DLSim.Util;
/* Generated by Together */

public interface Observable {
    void attach(Observer observer);

    void detach(Observer observer);

    void inform();

    /**
     * @link
     * @shapeType PatternLink
     * @pattern <{Observer}>
     * @supplierRole <{Observer}>
     * @hidden
     */
    /*# private Observer _observer; */
}
