package dlsim.DLSim.Util;
/* Generated by Together */

public interface Observer {
    void update();

    /**
     * @link
     * @shapeType PatternLink
     * @pattern <{Observer}>
     * @clientRole <{Observer}>
     * @supplierRole Subject
     */
    /*# private Observable _observable; */
}
